// @ts-expect-error - generated by `opennextjs-cloudflare build` before deploy
import { default as handler } from "./.open-next/worker.js";

/**
 * The Cloudflare entrypoint.
 *
 * Two things differ from the Node container:
 *
 * 1. Hyperdrive hands us the pooled Postgres connection string per request, so
 *    it is placed on process.env before the app's modules read it.
 * 2. There is no long-lived process, so webhook retries come from a Cron
 *    Trigger rather than a timer inside the app.
 *
 * Kept free of Workers-specific types so it needs no extra type packages; the
 * shapes below are the parts of the runtime this file actually touches.
 */

type Env = {
  HYPERDRIVE?: { connectionString: string };
  CRON_SECRET?: string;
  APP_URL?: string;
};

type Context = { waitUntil(promise: Promise<unknown>): void };

type NextHandler = {
  fetch(request: Request, env: unknown, ctx: Context): Promise<Response>;
};

const next = handler as NextHandler;

function applyBindings(env: Env): void {
  if (env.HYPERDRIVE?.connectionString) {
    process.env.DATABASE_URL = env.HYPERDRIVE.connectionString;
  }
}

const bothy = {
  async fetch(request: Request, env: Env, ctx: Context): Promise<Response> {
    applyBindings(env);
    return next.fetch(request, env, ctx);
  },

  async scheduled(_event: unknown, env: Env, ctx: Context): Promise<void> {
    applyBindings(env);

    if (!env.CRON_SECRET) {
      console.error("bothy: CRON_SECRET is not set, so webhook retries cannot run");
      return;
    }

    const base = (env.APP_URL ?? "https://bothy.invalid").replace(/\/$/, "");
    const request = new Request(`${base}/api/internal/webhooks`, {
      method: "POST",
      headers: { "x-bothy-cron-secret": env.CRON_SECRET },
    });

    const response = await next.fetch(request, env, ctx);
    if (!response.ok) {
      console.error(`bothy: webhook delivery returned ${response.status}`);
    }
  },
};

export default bothy;
